#!/usr/bin/env python3
import sys

def install(target, source):
    with open(source, "rb") as fp:
        boot = fp.read()
    with open(target, "r+b") as fp:
        fp.seek(0)
        original = fp.read(512)
        boot = boot[0:440] + original[440:510] + boot[510:]
        fp.seek(0)
        fp.write(boot)

def main():
    target = sys.argv[1]
    source = sys.argv[2]
    install(target, source)

if __name__ == "__main__":
    main()
